### ISSUE TITLE
Will this package provide a simple web interface?

### ISSUE THREAD

**Issue by stardiviner** [ndwarshuis/org-sql#1]
I like this idea! really great. Can it provide to view data in web with a simple local server and simple web dashboard page? Emacs has already local web server support with package like `elnode`, `web-server`, `simple-httped` etc. WDYT?

**Comment by ndwarshuis** [comment]
Thank you :smile: 

A web interface is the long term vision in fact, but not necessarily with this package. I'm working on an `R-shiny` app which will provide a local webserver to display visuals and perform analytics. I say R-shiny (or I guess I could use `python-pandas/dash`) because this sort of thing is exactly `R-shiny`'s use case, and I already know how to use it :wink: 

Is there a reason you suggest to use `elnode` and friends for this?

**Comment by stardiviner** [comment]
> Thank you smile
> 
> A web interface is the long term vision in fact, but not necessarily with this package. I'm working on an `R-shiny` app which will provide a local webserver to display visuals and perform analytics. I say R-shiny (or I guess I could use `python-pandas/dash`) because this sort of thing is exactly `R-shiny`'s use case, and I already know how to use it wink

That will be great! You might want to add that `R-shiny` app link to this repo README. That's will be helpful for me.

> Is there a reason you suggest to use `elnode` and friends for this?

Well, if use Emacs side packages, it will be more easy to integrate or something else... I guess. Not very specificly really.

And thanks for this package, I always try to do similar thing. You know, I use Org Mode to manage almost anything on computer, GTD, Wiki, diary journal, blog, dotfiles, programming, media manager. So I always try to integrate Org Mode with web, so available for web access will be awesome. Your `org-sql` provide an smart idea for this. so ... you know how thanksful I am. I'm still now skillful enought to participate in. But I will check out your source code, might contribute some minor helpful change, if you like it.

**Comment by ndwarshuis** [comment]
the web interface is WIP but will link to readme here when finished

**Comment by plur9** [comment]
Vote for python and dash! :)
