### ISSUE TITLE
Symbol’s function definition is void: org-ml-headline-get-logbook

### ISSUE THREAD

**Issue by jarofromel** [ndwarshuis/org-sql#10]
I've updated org-sql from version 1.01 to 1.1 and the following error appears when I try to update the database (sqlite database).

>  Symbol’s function definition is void: org-ml-headline-get-logbook

What I tried to solve it:
- clear, reset the database -> still error
- create the new database -> still error
- create the new database (only one simple org file is the input, i.e. the value of `org-sql-files`) -> OK

So it seems to me, that some of my org-mode files, which were parsed successfully in the previous version, are source of the error in the new version.

I have dozens of org-mode files. Do you have an idea what should I look for?

**Comment by ndwarshuis** [comment]
`org-ml-headline-get-logbook` was taken out in version 1.1.0. Can you grep your package directory and see where that function is? I'm guessing a file didn't get updated properly.

**Comment by jarofromel** [comment]
Yes, probably the update problem (not the issue of org-sql, rather the of issue my install of doom-emacs). After the manual deletion of files related to org-sql and the new install, the problem was resolved.
