### ISSUE TITLE
Effort not showing up in headlines table

### ISSUE THREAD

**Issue by rwalkerands** [ndwarshuis/org-sql#12]
Hmm, I don't see any `effort` values in the `headlines` table; they're all `NULL`.
Trivial test file:
```
* Test
  :PROPERTIES:
  :Effort:   1h
  :END:
```

Result after running `M-x org-sql-user-update`:

```
sqlite> select headline_text, effort from headlines;
Test|
```

(I've configured only `org-sql-files` and `org-sql-db-config` to be the input org-mode file and the output sqlite file, respectively; no other changes to `org-sql` variables. Emacs 27.1 on Mac.)

**Comment by ndwarshuis** [comment]
d355c82affbe3188b5ca415f7d4f511b1c0d2110 should fix this

**Comment by rwalkerands** [comment]
It does; thank you.
