### ISSUE TITLE
Documentation error - "org-sqlite-db-path" should be "org-sql-sqlite-path"

### ISSUE THREAD

**Issue by vonHabsi** [ndwarshuis/org-sql#5]
The value `org-sqlite-db-path` mentioned at [https://github.com/ndwarshuis/org-sql#general-behavior](https://github.com/ndwarshuis/org-sql#general-behavior) should be `org-sql-sqlite-path`.

 `org-sqlite-db-path` cannot be found in a search of the code.

**Comment by ndwarshuis** [comment]
indeed, thank you for pointing that out

closed with 003845f5a03417ef30c34d952bd013b1256af873
